[tasks.update]
description = "update scoop, winget, bun, mise"
run = "mise cleanup and scoop update * and winget upgrade --all and bun update -g and mise upgrade and mise self-update -y and rustup update stable"


# chezmoi tasks
[tasks.chezmoi-update-and-push]
description = "chezmoi update and push"
run = "chezmoi re-add and git commit -m update and git push -u origin main"



[tasks.cleanup]
description = "cleanup"
run = "scoop cleanup * and mise prune"


[tasks.commit]
description = "commit"
run = "git add . and czg ai" 


[tasks.start-podman]
description = "start podman"
run = "podman machine start" 






#[tasks.commitfile]
#description = "commit file"
#run = "!f() { git add \"$1\" and czg ai }; f"  

[tasks.copy-path]
description = "copy current path"
run = "(Get-Location).Path | Set-Clipboard"


[env]
OPENAI_API_KEY = "${env:OPENAI_API_KEY}"
